// <auto-generated />
namespace NewBIGprojectASOUME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WTHISGOINGON : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WTHISGOINGON));
        
        string IMigrationMetadata.Id
        {
            get { return "202206252216309_WTHISGOINGON"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
