// <auto-generated />
namespace NewBIGprojectASOUME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PROBABLYTOGOBACK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PROBABLYTOGOBACK));
        
        string IMigrationMetadata.Id
        {
            get { return "202206282353549_PROBABLY TO GO BACK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
